### ISSUE TITLE
as google code is now archived, so now the binary (.jar) should be distributed from bintray.com

### ISSUE THREAD

**Issue by zaxebo1** [arthurblake/log4jdbc#73]
as google code is now archived, so now the binary (.jar) should be distributed from bintray.com
bintray.com connects to github.com too

**Comment by arthurblake** [comment]
What does that buy me over just distributing them on github?
re: https://help.github.com/articles/distributing-large-binaries/

**Comment by zaxebo1** [comment]
:-) nothing.
Rather is better to use github. And i noticed that you have already released binaries available on github.

Now the only small request left is that in the https://github.com/arthurblake/log4jdbc/blob/master/README.md   , you may like to change the url for downloading the prebuilt jars

**Comment by arthurblake** [comment]
Thank you. I am planning to update the README.md later.
