### ISSUE TITLE
Executed in 0 msec

### ISSUE THREAD

**Issue by cleankod** [arthurblake/log4jdbc#77]
How come the sql timing sometimes shows that the statement has been executed in 0 msec? I have statement caching of the JDBC driver (both Log4jdbc and Oracle's) turned off. I am using Oracle's official JDBC driver.

**Comment by arthurblake** [comment]
This is completely normal. It just means that this particular SQL is running really quickly. The tick resolution of the timing method we use (System.currentTimeMillis) can be inaccurate up to 10 msec or more, depending on your platform, so if your SQL is running faster then that, then 0 can be reported.
