### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by CyborTronik** [arthurblake/log4jdbc#78]
Hi,
Is still alive?
Is this jar published to maven?

**Comment by sepe81** [comment]
You can find the last release in maven central -- see http://mvnrepository.com/artifact/com.googlecode.log4jdbc/log4jdbc

**Comment by arthurblake** [comment]
Yes it's still alive. There is a 1.3 code release which I haven't had time to formally release but you can build it from source. I don't do Maven but someone else out there puts it in Maven sometimes.

**Comment by sepe81** [comment]
@arthurblake Do you know the one who could possibly upload version 1.3 to maven? It would be a pitty, if this never happens, because IMO the project is of great value and most projects use maven dependencies nowadays. Thanks for all the great work!
