### ISSUE TITLE
Request for Scala/Play implementation details in the docs 

### ISSUE THREAD

**Issue by techmag** [arthurblake/log4jdbc#79]
This appears to solve a particular problem for a sub-set of Scala/Play developers using Anorm. (I'm sure it solves many other problem set as well...) 

Here ( http://stackoverflow.com/a/34175253/2162886 ) is some indication of how it might be incorporated into Play - I will be vetting this in my environment soon enough as it would be nice to actually see SQL queries as the DB sees them - especially when things blow up -- but I suspect I'm preaching to the choir :)

Close this issue unless you wish an update from me to confirm the above details in the link works as advertised.

**Comment by arthurblake** [comment]
Looks like maybe log4jdbc was confused with https://code.google.com/p/log4jdbc-log4j2/ (a fork of log4jdbc)

**Comment by techmag** [comment]
Thank you for the reply - I think I get it now :)
