### ISSUE TITLE
Unable to get string of query using driverspy

### ISSUE THREAD

**Issue by ishubhamjain** [arthurblake/log4jdbc#93]
I am working on a project where I need to log query in Log files and add those queries to my assert statement as well

I have build prepared statements using below driver

net.sf.log4jdbc.sql.jdbcapi.DriverSpy
And url

jdbc:log4jdbc:sybase:Tds ........
I have search all over the Internet for the solution but didn't get anything

Can you please tell me if there any way around by which I can get query which are getting logged in log file as well as in my code

I have raise question on stack as well

https://stackoverflow.com/questions/53505711/unable-to-get-string-of-query-using-driverspy

**Comment by arthurblake** [comment]
Your question is confusing and very unclear. It appears that you are just asking about basic usage of log4jdbc. For that you should read the instructions at https://code.google.com/archive/p/log4jdbc/ very carefully. Also, the driver class should be "net.sf.log4jdbc.DriverSpy" (not "net.sf.log4jdbc.sql.jdbcapi.DriverSpy").

**Comment by ishubhamjain** [comment]
@arthurblake - I want the prepared statement queries in variables as well.
I have update and explain the more detail in below stack question:

https://stackoverflow.com/questions/53589859/unable-to-get-string-of-query-using-driverspy

Please let me know if I am missing anything

**Comment by ishubhamjain** [comment]
I am working on a project where I need to log query in Log files and add those queries to my assert statement as well

I have build prepared statements using below driver

net.sf.log4jdbc.sql.jdbcapi.DriverSpy
And url

jdbc:log4jdbc:sybase:Tds ........ 
Dependencies I am using is as below:

    <dependency>
        <groupId>net.sourceforge.jtds</groupId>
        <artifactId>jtds</artifactId>
        <version>1.3.1</version>
    </dependency>
PrepareStatement Example:

public void getTest(MyBean bean) {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            conn = DatabaseUtil.getDatabaseConnection();
            ps = conn.prepareStatement(objTestQueryUtil.getQuery("GET_Test"));
            ps.setString(1, bean.getTypeOfTest());
            ps.setString(2, bean.getTest());
            ps.setString(3, bean.getTestState());
            ps.setString(4, bean.getTestStep());
            rs = ps.executeQuery();
            while(rs.next()) {
                bean.setTest(rs.getInt("Test"));
            }
        }catch (SQLException e) {
            AutomationLog.error(e.getMessage(),e);
        }finally {
            DatabaseUtil.close(conn,ps,rs);
        }
    }
In my assert class, the sql should see in my assert code like:

Assert.assertTrue("Got Test "+query, true);
Can you please tell me if there any way around by which I can get query in variables in java also, currently query directly logs into the log file and I am not able to find anyway by which I can get them in my script, i.e store on any variable etc

**Comment by arthurblake** [comment]
You are not using the log4jdbc library. Driver class you specified is from a different library - probably a fork of log4jdbc.
