### ISSUE TITLE
Feature Request: Ability to modify the data 

### ISSUE THREAD

**Issue by mjegann5** [arthurblake/log4jdbc#94]
I have an use case where we need to taansform the data inserted/updated to the database as well as the data retrieved from the database by the queries. I would like to write the transformation logic in java. Is there a way to do this using the log4jdbc?  Thanks.

**Comment by arthurblake** [comment]
The purpose of the library is to be as transparent as possible just for logging.
Perhaps fork the library or make a new library for your purpose?
Thank you.
